Repository coala/coala-quickstart, pull requests merged in 2018-06, with the labels that each got.

#233 README.rst: Change instructions for dev version
  README.rst
Labels: difficulty/newcomer, process/approved, size/XS

#251 ISSUE_TEMPLATE.md: Add template
  ISSUE_TEMPLATE.md
Labels: difficulty/newcomer, process/approved, size/XS, status/STALE

#255 test-requirements.txt: Use moban template
  .moban.yaml
  requirements.txt
  test-requirements.txt
Labels: process/approved, size/XS

#258 Fix a typo
  coala_quickstart/generation/Bears.py
Labels: difficulty/newcomer, process/approved, size/XS, type/bug

#259 test-requirements.txt: Use pytest 3.6
  test-requirements.txt
Labels: process/approved, size/XS

#253 Remove discrepancy in help message
  coala_quickstart/Strings.py
  coala_quickstart/coala_quickstart.py
  tests/generation/FileGlobs.py
  tests/interaction/Logo.py
Labels: question, size/XS
