Repository coala/coala-quickstart, pull requests merged in 2018-07, with the labels that each got.

#72 Utilites.py: Add language detection from hashbang
  coala_quickstart/Constants.py
  coala_quickstart/generation/Project.py
  coala_quickstart/generation/Utilities.py
  tests/generation/UtilitiesTest.py
Labels: difficulty/medium, process/pending review, size/XS, status/STALE

#270 test-requirements.txt: Sync with changes in moban
  .ci/appveyor.yml
  setup.py
  test-requirements.txt
Labels: size/S

#236 FileGlobs.py: Recursively look for gitignore files
  coala_quickstart/generation/FileGlobs.py
  coala_quickstart/generation/Utilities.py
  tests/generation/FileGlobs.py
  tests/generation/file_globs_gitignore_testfiles/another_folder/another_file.c
  tests/generation/file_globs_gitignore_testfiles/another_folder/script.js
  tests/generation/file_globs_gitignore_testfiles/data/example.py
  tests/generation/file_globs_gitignore_testfiles/data/sample/index.css
  tests/generation/file_globs_gitignore_testfiles/data/sample/index.html
Labels: difficulty/low, process/approved, size/XS, status/STALE
