Repository coala/coala-quickstart, pull requests merged in 2018-08, with the labels that each got.

#284 Settings.py: Unused variables removed
  coala_quickstart/generation/Settings.py
Labels: difficulty/newcomer, process/pending review, size/XS, type/style

#290 Add green mode incompatible bears list
  coala_quickstart/Constants.py
  coala_quickstart/generation/Bears.py
  tests/generation/BearsTest.py
Labels: process/approved, size/XS

#291 Project.py: Ask to select languages
  coala_quickstart/Constants.py
  coala_quickstart/coala_quickstart.py
  coala_quickstart/generation/Project.py
  tests/generation/BearsTest.py
  tests/generation/ProjectTest.py
Labels: process/approved, size/S

#206 requirements.txt: Unpin lxml version
  .ci/appveyor.yml
  .moban.yaml
  requirements.txt
Labels: process/pending review, size/XS

#305 Sync templates
  setup.cfg
  setup.py
  test-requirements.txt
Labels: process/pending review, size/XS

#296 green_mode: Choose job count based on environment
  coala_quickstart/green_mode/green_mode.py
  tests/green_mode/green_modeTest.py
Labels: process/approved, size/S

#306 green_modeTest.py: Remove test_unified_results
  tests/green_mode/green_modeTest.py
Labels: difficulty/newcomer, process/pending review, size/XS, type/style, type/tests

#308 .travis.yml: Add ntlk_data in cache directories
  .travis.yml
Labels: area/CI, difficulty/newcomer, process/pending review, size/XS
