Repository coala/coala-quickstart, pull requests merged in 2018-05, with the labels that each got.

#217 .coafile: Ignore pycodestyle errors
  .coafile
Labels: difficulty/low, importance/high, process/pending review, size/XS

#205 .gitignore: Add .DS_Store
  .gitignore
Labels: difficulty/newcomer, process/pending review, size/XS, status/STALE

#213 Add .editorconfig file
  .editorconfig
Labels: difficulty/low, process/pending review, size/XS

#215 .travis.yml: Enable travis-buddy
  .travis.yml
Labels: process/approved, size/XS, status/blocked

#225 EditorconfigParsing.py: Correct function name
  coala_quickstart/info_extractors/EditorconfigParsing.py
Labels: difficulty/low, importance/high, process/pending review, size/XS, type/bug

#231 .coafile: Remove deprecated Default section and apply QuotesBear
  .coafile
  coala_quickstart/Constants.py
  coala_quickstart/Strings.py
  coala_quickstart/coala_quickstart.py
  coala_quickstart/generation/Bears.py
  coala_quickstart/generation/FileGlobs.py
  coala_quickstart/generation/InfoCollector.py
  coala_quickstart/generation/InfoMapping.py
  coala_quickstart/generation/Project.py
  coala_quickstart/generation/Settings.py
  coala_quickstart/generation/SettingsFilling.py
  coala_quickstart/generation/Utilities.py
  coala_quickstart/info_extraction/Info.py
  coala_quickstart/info_extraction/InfoExtractor.py
  coala_quickstart/info_extraction/InfoScope.py
  coala_quickstart/info_extraction/Information.py
  coala_quickstart/info_extraction/Utilities.py
  coala_quickstart/info_extractors/EditorconfigInfoExtractor.py
  coala_quickstart/info_extractors/EditorconfigParsing.py
  coala_quickstart/info_extractors/GemfileInfoExtractor.py
  coala_quickstart/info_extractors/GruntfileInfoExtractor.py
  coala_quickstart/info_extractors/PackageJSONInfoExtractor.py
  coala_quickstart/info_extractors/Utilities.py
  coala_quickstart/interaction/Logo.py
  setup.py
Labels: difficulty/low, difficulty/newcomer, process/approved, size/L, status/STALE
